alter table comic.title
	add index (image_id),
	add constraint title__image__fk
                foreign key (image_id)
		references image (id),
	add index (title_type_id),
	add constraint title__title_type__fk
                foreign key (title_type_id)
		references title_type (id);
